apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mikopbx-cf-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.cf.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mikopbx-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}
