apiVersion: v1
kind: Service
metadata:
  name: mikopbx-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mikopbx
  ports:
    - name: web
      port: {{ .Values.pbxConfig.webPort }}
      targetPort: {{ .Values.pbxConfig.webPort }}
      nodePort: {{ .Values.service.nodePorts.web }}
    - name: https
      port: {{ .Values.pbxConfig.httpsPort }}
      targetPort: {{ .Values.pbxConfig.httpsPort }}
      nodePort: {{ .Values.service.nodePorts.https }}
    - name: ssh
      port: {{ .Values.pbxConfig.sshPort }}
      targetPort: {{ .Values.pbxConfig.sshPort }}
      nodePort: {{ .Values.service.nodePorts.ssh }}
